# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "rios-reaper"

[default.build.parameters]
cached = true
parallel = true
build_image = "public.ecr.aws/sam/build-python3.12:latest-arm64"
use_container = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
region = 'us-west-2'

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local.parameters]
skip_pull_image = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
